---
title: "3_3 Labels"
author: "Wal McConnell"
date: "18 June 2017"
output: html_document
---

## 3.2 Labels

```{r setup, include=FALSE}
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
df <- data.frame(
  x = 1,
  y = 3:1,
  family = c("sans", "serif", "mono"),
  face = c("plain", "bold", "italic")
)
p <- ggplot(df, aes(x,y))
```


```{r}
plot(p + geom_text(aes(label = family, family = family, fontface = face)))
```

``` {r}
df <- data.frame(
  x = c(1,1,2,2,1.5),
  y = c(1,2,1,2,1.5),
  text = c("bottom-left", "bottom-right", "top-left", "top-right", "center")
  )

plot(ggplot(df, aes(x,y)) + geom_text(aes(label = text), vjust = 'inward', hjust='inward'))

```

```{r}
df <- data.frame(
  x = c(1,1,2,2,1.5),
  y = c(1,2,1,2,1.5),
  text = c("bottom-left", "bottom-right", "top-left", "top-right", "center"),
  size = 10:14,
  angle = seq(0,300, length.out = 5)
  )

plot(ggplot(df, aes(x,y)) + geom_text(aes(label = text, size = size, angle = angle), vjust = 'inward', hjust='inward') + xlim(1,3) + ylim(0,3))
```

```{r}
p <- ggplot(mpg, aes(displ, hwy))
plot(p + geom_text(aes(label = model)) + xlim(1,6))
```

```{r}
p <- ggplot(mpg, aes(displ, hwy))
plot(p + geom_text(aes(label = model), check_overlap = TRUE) + xlim(1,6))
```


```{r}
df <- data.frame(
  waiting = c(55, 80),
  eruptions = c(2,4.3),
  label = c("peak one", "peak two")  
)
p <- ggplot(faithfuld, aes(waiting, eruptions))
plot(p + geom_tile(aes(fill = density)))
```


```{r}
df <- data.frame(
  waiting = c(55, 80),
  eruptions = c(2,4.3),
  label = c("peak one", "peak two")  
)
p <- ggplot(faithfuld, aes(waiting, eruptions))
plot(p + geom_tile(aes(fill = density)) + geom_label(data = df, aes(label = label)))
```

```{r}
p <- ggplot(mpg, aes(displ, hwy, color = class))
plot(p + geom_point())
```

```{r}
library(directlabels)
p <- ggplot(mpg, aes(displ, hwy, color = class))
plot(p + geom_point(show.legend = FALSE) + directlabels::geom_dl(aes(label = class), method = 'smart.grid'))
```