---
title: "3_5 Collective Geoms"
author: "Wal McConnell"
date: "18 June 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```
s
```{r cars}
data(Oxboys, package = "nlme")
head(Oxboys)

p <- ggplot(Oxboys, aes(age, height, group = Subject))
plot(p + geom_point() + geom_line())
```

```{r}
p <- ggplot(Oxboys, aes(age, height))
plot(p +  geom_point() +geom_line())
```

```{r}
ggplot(Oxboys, aes(age, height, group = Subject)) +
  geom_line() +
  geom_smooth(method = "lm", se = FALSE)
```


```{r}
p <- ggplot(Oxboys, aes(age, height))
plot(p + geom_line(aes(group = Subject)) + geom_smooth(method = "lm", size = 2, se = FALSE))
```


```{r}
p <- ggplot(Oxboys, aes(Occasion, height))
plot(p + geom_boxplot())
```


```{r}
p <- ggplot(Oxboys, aes(Occasion, height))
plot(p + 
  geom_boxplot() +
  geom_line(colour = "#3366FF", alpha = 0.5))
```

```{r}
p <- ggplot(Oxboys, aes(Occasion, height))
plot(p + geom_boxplot() + geom_line(aes(group = Subject), colour = "#3366FF", alpha = 0.5))
```


```{r}
df <- data.frame(x = 1:3, y = 1:3, colour = c(1,3,5))
p <- ggplot(df, aes(x, y, colour = factor(colour)))
plot(p + geom_line(aes(group = 1), size = 2) + geom_point(size = 5))
```


```{r}
df <- data.frame(x = 1:3, y = 1:3, colour = c(1,3,5))
p < -ggplot(df, aes(x, y, colour = colour))
plot(p  + geom_line(aes(group = 1), size = 2) + geom_point(size = 5))
```

